logging:
  level:
     org:
       springframework:
         security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/auth
    username: root
    password: password
    driver-class: com.mysql.jdbc.Driver